/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BohofitRouteImport } from './routes/bohofit'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as CafeRouteImport } from './routes/cafe'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DietRouteImport } from './routes/diet'
import { Route as FiftyplusRouteImport } from './routes/fiftyplus'
import { Route as LongevityRouteImport } from './routes/longevity'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as FamilyTokenRouteImport } from './routes/family.$token'
import { Route as LongevityMeRouteImport } from './routes/longevity.me'
import { Route as MethodSlugRouteImport } from './routes/method.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BohofitRoute = BohofitRouteImport.update({
  id: '/bohofit',
  path: '/bohofit',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const CafeRoute = CafeRouteImport.update({
  id: '/cafe',
  path: '/cafe',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DietRoute = DietRouteImport.update({
  id: '/diet',
  path: '/diet',
  getParentRoute: () => rootRouteImport,
} as any)
const FiftyplusRoute = FiftyplusRouteImport.update({
  id: '/fiftyplus',
  path: '/fiftyplus',
  getParentRoute: () => rootRouteImport,
} as any)
const LongevityRoute = LongevityRouteImport.update({
  id: '/longevity',
  path: '/longevity',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const FamilyTokenRoute = FamilyTokenRouteImport.update({
  id: '/family/$token',
  path: '/family/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LongevityMeRoute = LongevityMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => LongevityRoute,
} as any)
const MethodSlugRoute = MethodSlugRouteImport.update({
  id: '/method/$slug',
  path: '/method/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/bohofit': typeof BohofitRoute
  '/booking': typeof BookingRoute
  '/cafe': typeof CafeRoute
  '/dashboard': typeof DashboardRoute
  '/diet': typeof DietRoute
  '/fiftyplus': typeof FiftyplusRoute
  '/longevity': typeof LongevityRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/family/$token': typeof FamilyTokenRoute
  '/longevity/me': typeof LongevityMeRoute
  '/method/$slug': typeof MethodSlugRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/bohofit': typeof BohofitRoute
  '/booking': typeof BookingRoute
  '/cafe': typeof CafeRoute
  '/dashboard': typeof DashboardRoute
  '/diet': typeof DietRoute
  '/fiftyplus': typeof FiftyplusRoute
  '/longevity': typeof LongevityRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/family/$token': typeof FamilyTokenRoute
  '/longevity/me': typeof LongevityMeRoute
  '/method/$slug': typeof MethodSlugRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/bohofit': typeof BohofitRoute
  '/booking': typeof BookingRoute
  '/cafe': typeof CafeRoute
  '/dashboard': typeof DashboardRoute
  '/diet': typeof DietRoute
  '/fiftyplus': typeof FiftyplusRoute
  '/longevity': typeof LongevityRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/family/$token': typeof FamilyTokenRoute
  '/longevity/me': typeof LongevityMeRoute
  '/method/$slug': typeof MethodSlugRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/bohofit'
    | '/booking'
    | '/cafe'
    | '/dashboard'
    | '/diet'
    | '/fiftyplus'
    | '/longevity'
    | '/privacy'
    | '/app/onboarding'
    | '/family/$token'
    | '/longevity/me'
    | '/method/$slug'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/bohofit'
    | '/booking'
    | '/cafe'
    | '/dashboard'
    | '/diet'
    | '/fiftyplus'
    | '/longevity'
    | '/privacy'
    | '/app/onboarding'
    | '/family/$token'
    | '/longevity/me'
    | '/method/$slug'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/bohofit'
    | '/booking'
    | '/cafe'
    | '/dashboard'
    | '/diet'
    | '/fiftyplus'
    | '/longevity'
    | '/privacy'
    | '/app/onboarding'
    | '/family/$token'
    | '/longevity/me'
    | '/method/$slug'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  BohofitRoute: typeof BohofitRoute
  BookingRoute: typeof BookingRoute
  CafeRoute: typeof CafeRoute
  DashboardRoute: typeof DashboardRoute
  DietRoute: typeof DietRoute
  FiftyplusRoute: typeof FiftyplusRoute
  LongevityRoute: typeof LongevityRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  FamilyTokenRoute: typeof FamilyTokenRoute
  MethodSlugRoute: typeof MethodSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bohofit': {
      id: '/bohofit'
      path: '/bohofit'
      fullPath: '/bohofit'
      preLoaderRoute: typeof BohofitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cafe': {
      id: '/cafe'
      path: '/cafe'
      fullPath: '/cafe'
      preLoaderRoute: typeof CafeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diet': {
      id: '/diet'
      path: '/diet'
      fullPath: '/diet'
      preLoaderRoute: typeof DietRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiftyplus': {
      id: '/fiftyplus'
      path: '/fiftyplus'
      fullPath: '/fiftyplus'
      preLoaderRoute: typeof FiftyplusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/longevity': {
      id: '/longevity'
      path: '/longevity'
      fullPath: '/longevity'
      preLoaderRoute: typeof LongevityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/family/$token': {
      id: '/family/$token'
      path: '/family/$token'
      fullPath: '/family/$token'
      preLoaderRoute: typeof FamilyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/longevity/me': {
      id: '/longevity/me'
      path: '/me'
      fullPath: '/longevity/me'
      preLoaderRoute: typeof LongevityMeRouteImport
      parentRoute: typeof LongevityRoute
    }
    '/method/$slug': {
      id: '/method/$slug'
      path: '/method/$slug'
      fullPath: '/method/$slug'
      preLoaderRoute: typeof MethodSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppOnboardingRoute: AppOnboardingRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface LongevityRouteChildren {
  LongevityMeRoute: typeof LongevityMeRoute
}

const LongevityRouteChildren: LongevityRouteChildren = {
  LongevityMeRoute: LongevityMeRoute,
}

const LongevityRouteWithChildren = LongevityRoute._addFileChildren(
  LongevityRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  BohofitRoute: BohofitRoute,
  BookingRoute: BookingRoute,
  CafeRoute: CafeRoute,
  DashboardRoute: DashboardRoute,
  DietRoute: DietRoute,
  FiftyplusRoute: FiftyplusRoute,
  LongevityRoute: LongevityRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  FamilyTokenRoute: FamilyTokenRoute,
  MethodSlugRoute: MethodSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
